python main.py \
--audio_dir "/path/audio_feat_AST/" \
--visual_dir "/path/Swin_L_384_feature/" \
--video_dir "/path/VideoSwin_B_3D_feature" \
--label_train "/path/label_train.json" \
--label_val "/path/label_val.json" \
--label_test "/path/label_test.json" \
--batch_size 16 \
--lr 1e-4 \
--epochs 20 \
--eval_unc_logit_adj_ratio 5.0 \
--unc_rank_type 'sigmoid_sym' \
--sig_sym_th 2.0 \
--l2_weight_decay 0.000
